### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dawnos** [zju-rolab/thomas_drivers#1]
- [ ] 驱动程序
    - [x] 上版本管理。上github。（以后可以在github上提issue，包括本页）
    - [x] 代码整理
        - [x] 将与我们项目有关的改动分离出来，单独建立包（尽量保证驱动代码与原版的一致）
    - [x] counter_div，counter_rem（除数和余数。单片机端和PC端均要参数化，激光和相机的驱动都需要）
    - [ ] IMU驱动：
        - [x] 程序上解决latency_timer
        - [x] 根据SampleTime判断PacketCounter的周期数
        - [x] 智能添加权限（TL）
        - [ ] 信号干扰（加屏蔽）
        - [ ] IMU时钟不稳（GPS模式下）
    - [x] 相机驱动：
        - [x] 去掉ThroughPut，保留packet_delay
        - [x] 命名规范一下。gevs开头可以去掉
        - [ ] 读相机计数器
    - [x] 激光驱动：（暂无）
- [x] 总的启动脚本，总的采集脚本
- [ ] Docker化
- [ ] Deb 化
- [x] 加INS，加32线，整理线（以后）
- [ ] 加遮光罩
